/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import { MyName, MyNameElement } from './components/my-name/my-name';

interface MyNameElement extends MyName, HTMLElement {}

declare var HTMLMyNameElement: {
  prototype: MyNameElement;
  new (): MyNameElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "my-name": MyNameElement;
  }
  interface ElementTagNameMap {
      "my-name": MyNameElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "my-name": JSXElements.MyNameAttributes;
      }
  }
  namespace JSXElements {
      export interface MyNameAttributes extends HTMLAttributes {
        
          first?: any,
          last?: any
      }
  }
}

